version: '3'
services:
  topcoder-mm-submit:
    image: tanzaku/topcoder_mm_utils:latest
    container_name: "topcoder-mm-submit"
    tty: true
    volumes:
      - $PWD:/data
    working_dir: /data
    environment:
      - TZ=Asia/Tokyo
      - TC_USERNAME=
      - TC_PASSWORD=
      - CHALLENGE_ID=
      - SUBMIT_FILE_PATH=
      - SCREENSHOT_DIR=
      - DRY_RUN=
  topcoder-mm-standings-scrape:
    image: tanzaku/topcoder_mm_utils:latest
    container_name: "topcoder-mm-standings-scrape"
    tty: true
    environment:
      - TZ=Asia/Tokyo
      - TC_USERNAME=
      - TC_PASSWORD=
      - SCREENSHOT_DIR=
      - PG_DB_HOST=
      - PG_DB_USERNAME=
      - PG_DB_PASSWORD=
      - PG_DB_NAME=
      - PG_DB_PORT=
  