FROM alpine:latest

LABEL MAINTAINER=tanzaku

RUN apk add --update \
    udev \
    ttf-freefont \
    chromium \
    chromium-chromedriver \
    python3 \
    postgresql-dev \
    gcc libc-dev

RUN pip3 install --upgrade pip && \
    # pip install "chromedriver-binary<$(chrome --version | awk '{ print $NF }' )" && \
    pip install selenium

ADD src/main.py /app/bin/main.py

CMD ["python3", "/app/bin/main.py"]
