version: '3'
services:
  topcoder-mm-submit:
    image: tanzaku/topcoder_mm_utils:latest
    container_name: "topcoder-mm-submit"
    tty: true
    volumes:
      - $PWD:/data
    working_dir: /data
    environment:
      - TZ=Asia/Tokyo
      - USERNAME=tanzaku
      - PASSWORD=XXXXXXXX
      - CHALLENGE_ID=30092303
      - SUBMIT_FILE_PATH=/data/test/python-example.zip
      - SCREENSHOT_DIR=/data/screenshot
      # - DRY_RUN=1
